export enum ErrorCode {
  APP_ALREADY_ADDED = 'APP_ALREADY_ADDED',
  APP_FILE_NOT_FOUND = 'APP_FILE_NOT_FOUND',
  APP_NOT_ADDED = 'APP_NOT_ADDED',
  APP_NOT_FOUND = 'APP_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  LOGIN_ALREADY_EXISTS = 'LOGIN_ALREADY_EXISTS',
  TOO_MANY_EMAIL_REQUESTS = 'TOO_MANY_EMAIL_REQUESTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_EMAIL_SECRET = 'WRONG_EMAIL_SECRET',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
}
